#!/usr/bin/env sh

update() {
  sum=0
  for arg; do
    read -r i < "$arg"
    sum=$(( sum + i ))
  done
  cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
  [ -f "$cache" ] && read -r old < "$cache" || old=0
  printf %d\\n "$sum" > "$cache"
  printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)
traffic=$(printf "%4s  %4s \\n" $(numfmt --to=iec $rx) $(numfmt --to=iec $tx))

read -d "\n" -r SSID freq <<< $(iw dev wlp3s0 link | awk '/SSID|freq/ {print $2}')
if [ $freq -ge 5000 ]; then
  freq=" [5GHz]"
else
  freq=""
fi

wlan=""
prefix="ﯱ "
[ "$SSID" != "" ] && wlan=" $SSID$freq $(awk 'NR==3 {printf("%.0f%",$3*10/7)}' /proc/net/wireless)" && prefix=""

echo -e "\x0e$prefix$wlan $traffic\x0b"
