#!/usr/bin/env sh

mute=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d ' ' -f 2)

case $mute in
  yes)
    vol="--"
    ;;
  no)
    vol="$(pactl get-sink-volume @DEFAULT_SINK@ |\
      head -n 1 | sed 's/.* \([0-9][0-9]*\)%.*/\1/')"
    [ $vol -gt 100 ] && vol="\x0c$vol"
    ;;
esac

echo -e "\x0f $vol\x0b"
