#!/usr/bin/env sh
# script to quickly edit my scripts using dmenu

SCRIPTS_DIR=$HOME/.local/bin/dmenu

choice=$(/bin/ls $SCRIPTS_DIR | sed 's/dmenu-//' | dmenu -i -p "edit")
[ -z $choice ] && exit # handling no choice
edit=$SCRIPTS_DIR/dmenu-$choice

alacritty -e nvim $edit && $HOME/.local/bin/refresh_keys
