#!/bin/sh

# Edit config files with dmenu

TERMINAL=st
XDG_CONFIG_DIR="$HOME/.config"
ENTRIES="alacritty\naliases\nbash\ndunst\nkeys\nneovim\npicom\nstartpage\nzathura\nzsh\nxresources\nfunctions\nconfig"
edit=$(echo -e $ENTRIES | dmenu -p "config" -i)
cwd=$HOME

case $edit in
  aliases)
    path=$XDG_CONFIG_DIR/shell/aliasrc
    ;;
  zsh)
    path=$HOME/.zshrc
    ;;
  alacritty)
    path=$XDG_CONFIG_DIR/alacritty/alacritty.yml
    ;;
  dunst)
    path=$XDG_CONFIG_DIR/dunst/dunstrc
    ;;
  picom)
    path=$XDG_CONFIG_DIR/picom/picom.conf
    ;;
  neovim)
    cwd=$XDG_CONFIG_DIR/nvim/
    path=$XDG_CONFIG_DIR/nvim/init.vim
    ;;
  keys)
    path=$XDG_CONFIG_DIR/sxhkd/sxhkdrc
    ;;
  bash)
    path=$HOME/.bashrc
    ;;
  zathura)
    path=$XDG_CONFIG_DIR/zathura/zathurarc
    ;;
  xresources)
    path=$XDG_CONFIG_DIR/X11/Xresources
    ;;
  startpage)
    path=$HOME/.local/src/linux/startpage/index.html
    ;;
  functions)
    path=$HOME/.config/shell/functions
    ;;
  config)
    path=$HOME/.local/bin/dmenu/dmenu_config
    ;;

  *)
    exit
    ;;
esac

$($TERMINAL --working-directory $cwd -e nvim $path)
