#!/usr/bin/env bash
# author: Marco Radocchia

notify-send -t 1500 "Network" "Looking for WiFi networks"
choice=$(nmcli -f BSSID,SSID,RATE,SECURITY,BARS dev wifi | sed '1d' |\
  sort | dmenu -i -p network -l 10)
[ -z "$choice" ] && exit  # handling no choice
bssid=$(echo "$choice" | awk '{print $1}')
ssid=$(nmcli -f BSSID,SSID dev wifi | grep $bssid |\
  # TODO: not very elegant solution
  sed 's/^[A-Z0-9][A-Z0-9]:[A-Z0-9][A-Z0-9]:[A-Z0-9][A-Z0-9]:[A-Z0-9][A-Z0-9]:[A-Z0-9][A-Z0-9]:[A-Z0-9][A-Z0-9] \(.*\)/\1/' |\
  awk '{print $1}')

# 1 -> known; 0 -> not
known=$(nmcli connection show | grep "^${ssid} " | wc -l)

# TODO: add option for non secured network
if [ $known -eq 1 ]; then
  nmcli dev wifi connect $bssid > /dev/null &&\
    notify-send -t 1000 "Network" "Connection activated"
else
  password="$(dmenu -p "password" -P)"
  [ -z "$password" ] && exit
  nmcli dev wifi connect $bssid password $password > /dev/null &&\
    notify-send -t 1000 "Network" "Connection activated"
fi
