#!/bin/python
from os.path import expanduser
from os import popen
from sys import argv

"""
this brightness in range [0-100]
xrandr's brightness in range [0-10]
"""

def main():
    with open(expanduser('~/.local/share/dwm/displaybrightness'), 'r') as brightfile:
        brightness = int(brightfile.read().strip('\n'))
    if len(argv) < 2: return # If no argument exit
    val = int(argv[1])
    brightness = (brightness + val) / 100
    if brightness < 0.1 or brightness > 1: return # Values less than 0.2 or more than 1 are distorting the image
    popen(f'xrandr --output DP-2 --brightness {brightness} && echo {str(int(brightness * 100))} > ~/.local/share/dwm/displaybrightness')
    return

if __name__ == '__main__':
    main()
